# Generated by Codex
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_snapshot_created_at_and_costentry_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingBlobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path_template', models.TextField(help_text='Use placeholders {billing_period} and {guid} in the template')),
                ('guid', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.subscription')),
            ],
            options={'unique_together': {('subscription', 'guid')}},
        ),
        migrations.RemoveField(
            model_name='importsnapshot',
            name='snapshot_date',
        ),
        migrations.AddField(
            model_name='importsnapshot',
            name='run_id',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importsnapshot',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsnapshot',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingblobsource'),
        ),
        migrations.AlterModelOptions(
            name='importsnapshot',
            options={'ordering': ['-created_at']},
        ),
    ]
