# Generated by Django 5.2.1 on 2025-05-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_costreportsnapshot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costreportsnapshot',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='in_progress', max_length=20),
        ),
    ]
